schema_version = "1.0.0"

id = "vlend"
version = "0.1.0"
name = "Vlend"
tagline = "Explore the X-ray scans from the Vesuvius Challenge"
maintainer = "Santiago Pelufo"
type = "add-on"

website = "https://scrollprize.org/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/latest/advanced/extensions/tags.html
# tags = ["Animation", "Sequencer"]

blender_version_min = "5.1.2"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/latest/advanced/extensions/licenses.html
license = [
  "SPDX:MIT",
]
copyright = [
  "2023-2026 Santiago Pelufo",
]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/latest/advanced/extensions/python_wheels.html
# wheels = [
#   "aiohappyeyeballs-2.7.1-py3-none-any.whl",
#   "aiohttp-3.14.3-cp314-cp314-macosx_11_0_arm64.whl",
#   "aiosignal-1.4.0-py3-none-any.whl",
#   "attrs-26.1.0-py3-none-any.whl",
#   "certifi-2026.7.22-py3-none-any.whl",
#   "charset_normalizer-3.5.1-cp314-cp314-macosx_10_15_universal2.whl",
#   "donfig-0.8.1.post1-py3-none-any.whl",
#   "frozenlist-1.8.0-cp314-cp314-macosx_11_0_arm64.whl",
#   "fsspec-2026.7.0-py3-none-any.whl",
#   "google_crc32c-1.8.0-cp314-cp314-macosx_12_0_arm64.whl",
#   "idna-3.19-py3-none-any.whl",
#   "lxml-6.1.3-cp314-cp314-macosx_10_15_universal2.whl",
#   "ml_dtypes-0.6.0-cp314-cp314-macosx_10_15_universal2.whl",
#   "multidict-6.7.1-cp314-cp314-macosx_11_0_arm64.whl",
#   "nest_asyncio-1.6.0-py3-none-any.whl",
#   "numcodecs-0.16.5-cp314-cp314-macosx_11_0_arm64.whl",
#   "numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl",
#   "packaging-26.3-py3-none-any.whl",
#   "pillow-12.3.0-cp314-cp314-macosx_11_0_arm64.whl",
#   "propcache-0.5.2-cp314-cp314-macosx_11_0_arm64.whl",
#   "pynrrd-1.1.3-py3-none-any.whl",
#   "pyyaml-6.0.3-cp314-cp314-macosx_11_0_arm64.whl",
#   "requests-2.34.2-py3-none-any.whl",
#   "tensorstore-0.1.85-cp314-cp314-macosx_11_0_arm64.whl",
#   "tqdm-4.70.0-py3-none-any.whl",
#   "typing_extensions-4.16.0-py3-none-any.whl",
#   "urllib3-2.7.0-py3-none-any.whl",
#   "vesuvius-0.1.10-py3-none-any.whl",
#   "yarl-1.24.5-cp314-cp314-macosx_11_0_arm64.whl",
#   "zarr-3.3.0-py3-none-any.whl",
# ]

# Optional: add-ons can list which resources they will require:
# * files (for access of any filesystem operations)
# * network (for internet access)
# * clipboard (to read and/or write the system clipboard)
# * camera (to capture photos and videos)
# * microphone (to capture audio)
#
# If using network, remember to also check `bpy.app.online_access`
# https://docs.blender.org/manual/en/latest/advanced/extensions/addons.html#internet-access
#
# For each permission it is important to also specify the reason why it is required.
# Keep this a single short sentence without a period (.) at the end.
# For longer explanations use the documentation or detail page.

[permissions]
network = "Download"
files = "Load/save"
clipboard = "Copy/paste"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/latest/advanced/command_line/extension_arguments.html#command-line-args-extension-build
# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
