#!/usr/bin/env python3
"""Package velend as a standalone extension zip.

Its Python dependencies are bundled as wheels, so that installing the zip is
all a user has to do.

	scripts/build.py                        # every platform in PLATFORMS
	scripts/build.py macos-arm64 linux-x64  # only the platforms named

Wheels are downloaded for Blender's Python version rather than for whatever
Python is running this, so one machine can build the packages for all of them.

	https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html
	https://docs.blender.org/manual/en/latest/advanced/extensions/python_wheels.html
"""

import argparse
import shutil
import sys

from blender_env import PROVIDED_BY_BLENDER, ROOT, Blender, fail


# Blender platform id, then the pip platform tags whose wheels its Python can
# load. Several tags per platform, because a wheel built against an older macOS
# or manylinux baseline still runs on a newer one.
PLATFORMS = {
	"macos-arm64": (
		"macosx_11_0_arm64", "macosx_12_0_arm64",
		"macosx_13_0_arm64", "macosx_14_0_arm64",
	),
	"macos-x64": (
		"macosx_10_13_x86_64", "macosx_11_0_x86_64",
		"macosx_12_0_x86_64", "macosx_13_0_x86_64",
	),
	"linux-x64": (
		"manylinux2014_x86_64", "manylinux_2_17_x86_64", "manylinux_2_28_x86_64",
	),
	"windows-x64": ("win_amd64",),
}

WHEELS_DIR = ROOT / "wheels"
BUILD_DIR = ROOT / "build"

# Delimit the part of the manifest these scripts own. The rest is hand written
# and is never touched.
BEGIN = "# BEGIN generated by scripts/build.py"
END = "# END generated"


def fetch_wheels(blender, platforms):
	"""Fill wheels/ with what `platforms` need, and nothing else.

	Blender installs the wheels a manifest lists whenever the extension is
	enabled, so this is as much what a development checkout needs as what goes
	into a package. Only build.py goes on to rewrite the manifest.
	"""
	download_wheels(blender, platforms)
	print()
	drop_provided_wheels()


def manifest_wheels():
	"""The wheel filenames the manifest currently lists."""
	names = []
	for line in (ROOT / "blender_manifest.toml").read_text().splitlines():
		line = line.strip()
		if line.startswith('"./wheels/'):
			names.append(line.rsplit("/", 1)[1].rstrip('",'))
	return names


def download_wheels(blender, platforms):
	"""Refill wheels/ with one set of wheels per platform."""
	print("== downloading wheels into %s" % WHEELS_DIR)
	if WHEELS_DIR.exists():
		shutil.rmtree(WHEELS_DIR)
	WHEELS_DIR.mkdir(parents=True)
	for platform in platforms:
		print("-- " + platform)
		tags = []
		for tag in PLATFORMS[platform]:
			tags += ["--platform", tag]
		blender.pip(
			"download",
			"--requirement", str(ROOT / "requirements.txt"),
			"--dest", str(WHEELS_DIR),
			# Required by --platform, and a wheel is what we need anyway.
			"--only-binary=:all:",
			"--python-version", blender.pytag,
			*tags,
			"--quiet",
		)


def drop_provided_wheels():
	print("== dropping wheels Blender already provides")
	for wheel in sorted(WHEELS_DIR.glob("*.whl")):
		# Wheel filenames are {name}-{version}-{tags}.whl, with the name
		# normalised to lowercase and '-' turned into '_'.
		project = wheel.name.split("-", 1)[0].lower().replace("_", "-")
		if project in PROVIDED_BY_BLENDER:
			print("-- " + wheel.name)
			wheel.unlink()


def toml_list(name, values):
	if not values:
		return ["# (no %s)" % name]
	return ["%s = [" % name] + ['  "%s",' % value for value in values] + ["]"]


def update_manifest(platforms):
	"""Rewrite the platform and wheel lists to match what was just built."""
	print("== updating the generated lists in blender_manifest.toml")
	wheels = sorted(wheel.name for wheel in WHEELS_DIR.glob("*.whl"))
	block = "\n".join(
		[BEGIN]
		+ toml_list("platforms", platforms)
		+ toml_list("wheels", ["./wheels/%s" % wheel for wheel in wheels])
		+ [END]
	)

	path = ROOT / "blender_manifest.toml"
	text = path.read_text(encoding="utf-8")
	start = text.find(BEGIN)
	stop = text.find(END, start + 1) if start != -1 else -1
	if start == -1 or stop == -1:
		fail("%s: expected the %r ... %r markers" % (path, BEGIN, END))
	updated = text[:start] + block + text[stop + len(END):]
	if updated != text:
		path.write_text(updated, encoding="utf-8")
	print("%d platform(s), %d wheel(s) listed" % (len(platforms), len(wheels)))


def build(blender, platforms):
	print("== validating")
	blender.command("extension", "validate", str(ROOT))
	print()

	print("== building")
	# Start clean, so that the zips left behind are exactly this build's.
	if BUILD_DIR.exists():
		shutil.rmtree(BUILD_DIR)
	BUILD_DIR.mkdir(parents=True)
	blender.command(
		"extension", "build",
		"--source-dir", str(ROOT),
		"--output-dir", str(BUILD_DIR),
		# One zip per platform, so that nobody downloads four platforms' binary
		# wheels in order to use one.
		"--split-platforms",
	)


def main(argv=None):
	parser = argparse.ArgumentParser(
		description=__doc__,
		formatter_class=argparse.RawDescriptionHelpFormatter,
	)
	parser.add_argument(
		"platforms", nargs="*", metavar="PLATFORM",
		help="platforms to build for (default: all of %s)" % ", ".join(PLATFORMS),
	)
	args = parser.parse_args(argv)
	platforms = args.platforms or list(PLATFORMS)
	unknown = [platform for platform in platforms if platform not in PLATFORMS]
	if unknown:
		fail("unknown platform(s): %s" % ", ".join(unknown))

	blender = Blender()
	print("blender:   %s" % blender.path)
	print("python:    %s" % blender.pytag)
	print("platforms: %s" % " ".join(platforms))
	print()

	fetch_wheels(blender, platforms)
	print()
	update_manifest(platforms)
	print()
	build(blender, platforms)

	print()
	for zipped in sorted(BUILD_DIR.glob("*.zip")):
		print("%8.1f MB  %s" % (zipped.stat().st_size / 1e6, zipped.name))


if __name__ == "__main__":
	sys.exit(main())
